# Generated by Django 4.2.1 on 2024-12-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Otchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otch', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Surnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('house', models.IntegerField(blank=True, null=True)),
                ('corpus', models.CharField(max_length=100)),
                ('apart', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('f_name_fk', models.ForeignKey(blank=True, db_column='name_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.firstnames')),
                ('otch_fk', models.ForeignKey(blank=True, db_column='otch_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.otchs')),
                ('street_fk', models.ForeignKey(blank=True, db_column='street_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.streets')),
                ('surname_fk', models.ForeignKey(blank=True, db_column='surname_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.surnames')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
