# Generated by Django 4.2.1 on 2024-12-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_apart_alter_main_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
